### ISSUE TITLE
Exogenous currency fee burning

### ISSUE THREAD

**Issue by enthusiastmartin** [galacticcouncil/hydration-node#117]
What I am thinking is that we might want to simplify this sooner than expected since this brings so many questions and probably performance implications. What we wanted to do with tx fees is to burn them instead of accumulating. Similar to EIP1559, but this brings some tokenomics questions which we didn't clear yet. 

Right now, we're doing User -> poolSwap (+token,-HDX) -> treasury. We could do just the burn and send on some very basic math really. 

Soo... The solution for me is to make it as simple as possible and create new issue that targets this in the omnipool.

_Originally posted by @jak-pan in https://github.com/galacticcouncil/HydraDX-node/pull/91#discussion_r583067221_

**Comment by jakubgregus** [comment]
I stand for burning all of them, as it will increase LPs earnings, buy pressure on HDX and decrease governance overhead with decisions about their usage. Also burning all of txs fees is preventing higher accumulation of HDX in hands of big stakers which is 1 of the main issues with all PoS systems where fees are redistributed to their validators.

**Comment by jak-pan** [comment]
We need to make sure there is no attack vector. I guess curated list of tokens that can be paid with is enough for now but if I enter the pool with SCAM coin and then start to spam everything and I am the sole owner of the SCAM coin, I'll be awarding myself coins for actions that are free becasue it goes back to me via the pool. Also I'm burning HDX supply.
