### ISSUE TITLE
Add Oracle Adapter that allows for arbitrary asset pair prices

### ISSUE THREAD

**Issue by apopiak** [galacticcouncil/hydration-node#543]
### Detailed Description
As a runtime developer I want to be able to query the price between any two assets in the omnipool. Currently the oracle only provides prices from/to LRNA. We can abstract over this by combining two prices to LRNA into one final price.

### Possible Implementation
Write a generic struct in the common runtime crate that takes two asset ids and returns their price.

cc @dmoka

**Comment by dmoka** [comment]
@apopiak For my DCA, I am already creating a `PriceProviderAdapter`, with signature
```
fn price(asset_a: AssetId, asset_b: AssetId) -> Option<Self::Price>
```

Where Price type is `EmaPrice`

I guess it should be sufficient enough?! What do you mean by generic struct, what do you want to abstract?
