### ISSUE TITLE
Support DCA for insufficient assets 

### ISSUE THREAD

**Issue by mrq1911** [galacticcouncil/hydration-node#772]
- [x] DCA takes transaction fee from the budget, in the case of insufficient assets this should be swapped immediately and not accumulated by the treasury
- [ ] insufficient assets are not tracked by oracle currently (DCA requires this)

**Comment by dmoka** [comment]
Added the feature here: https://github.com/galacticcouncil/hydration-node/pull/852

We won't track insufficient assets in oracle, we always swap them for DOT
