### ISSUE TITLE
Bug: release 29 reports runtime 207.0.0 node 12.0.0

### ISSUE THREAD

**Issue by dcolley** [galacticcouncil/hydration-node#871]
### Description

After download of the latest release 29, the executable reports an old version
### Expected Behavior

version should report runtime version hydradx/249 [as per release](https://github.com/galacticcouncil/hydration-node/releases/tag/v29.0.0)

### Actual Behavior

```
derek@dot-hdx-rpc1:~$ ./hydradx-29.0.0 --version
hydradx-29.0.0 23.1.0-320a008c runtime 207.0.0 node 12.0.0 x86_64-linux-gnu

derek@dot-hdx-rpc1:~$ ./hydradx-28.0.0 --version
hydradx-28.0.0 28.0.0-d5f7005e runtime 244.0.0 node 13.1.1 x86_64-linux-gnu
```

### Possible Fix

Recompile?

### Steps to Reproduce

1. wget https://github.com/galacticcouncil/hydration-node/releases/download/v29.0.0/hydradx
2. chmod +x hydradx
3. ./hydradx --version

### Your Environment

* Toolchain versions: 
* Version used: Github download
* System type:  Bare metal RPC server
* Operating System and version: Ubuntu
* System specs:

**Comment by mrq1911** [comment]
thank you for report, artifacts from https://github.com/galacticcouncil/hydration-node/releases/tag/v23.1.0 were attached by mistake instead

**Comment by dcolley** [comment]
Ok, just checked and it has the correct release now
