### ISSUE TITLE
Add sell all functions to router and AMMs

### ISSUE THREAD

**Issue by jak-pan** [galacticcouncil/hydration-node#883]
Similar to https://github.com/open-web3-stack/open-runtime-module-library/blob/23c8363d53fe8580f636a7f820c54b994d1b96f7/tokens/src/lib.rs#L522 this would allow us to create simpler UX and pass through functionality with XCM programs allowing better composability in similar sense that buy_for works for fee payment.

**Comment by dmoka** [comment]
We start with sell_all for router which solves the Max button issue.
