### ISSUE TITLE
Bug: TransactionPaymentApi_query_info panic for V3 or higher multiloc version when using with polkadotXcm.limitedReserveTransferAssets

### ISSUE THREAD

**Issue by nohaapav** [galacticcouncil/hydration-node#925]
### Description
TransactionPaymentApi_query_info panic for `V3` or higher multi-location version when using with `polkadotXcm.limitedReserveTransferAssets` if account has 0 balance of transferred asset. 

### Expected Behavior
Should return correct estimation as for V1/V2 multi-location

### Actual Behavior
Throw panic, with no paymentInfo details

### Steps to Reproduce
1. Try for example transfer from `kilt` to `hydration` with Alice (or another empty acc):
```
0x010104530803010100c91f03000101004554480026f5c2370e563e9f4dda435f03a63d7c109d8d0400000000000000000304000000000b00407a10f35a0000000000
```

**Comment by mrq1911** [comment]
can we fix this?
