### ISSUE TITLE
Standarize asset selection

### ISSUE THREAD

**Issue by dudo50** [galacticcouncil/hydration-node#940]
There are assets that have same name which makes it difficult for other devs to map them into SDKs

### Description
Our XCM SDK fails with error because there are multiple assets of same symbol - eg. WETH

### Actual status
WETH - 1000189, WETH - 4

### Expected status
Please differentiate assets in asset registry and do not allow for registering same asset symbol.

eg - first WETH from Wormhole can stay WETH and the other one can be for example WETH.e or something else. 

Thanks in advance!

**Comment by jak-pan** [comment]
Ticker is not unique identifier, assets should be mapped by their original id (Location/Multilocation in our case) which is an unique identifier, not the symbol or Name. There can be multiple assets with same ticker or name.

**Comment by dudo50** [comment]
@jak-pan, thanks for the information. We are currently introducing multilocation selection, so this will be fixed in the way you mentioned.
